server:
  port: ${CUSTOM.SERVER.PORT:9002}

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}

### Mongo database configuration
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mitocode
      # username:
      # password:
      uri: mongodb://mitocode:mitocode@localhost:27017
      authenticaion-database: admin
